from django.urls import path
from . import views

urlpatterns = [
    path('', views.OrderListView.as_view(), name='order_list'),
    path('<int:pk>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('<int:pk>/update/', views.order_update, name='order_update'),
    path('<int:pk>/cancel/', views.cancel_order, name='cancel_order'),
    path('<int:pk>/completion/', views.order_completion, name='order_completion'),
    path('<int:pk>/completion-info/', views.get_completion_info, name='get_completion_info'),
    path('change-status/', views.change_order_status, name='change_order_status'),
    path('export-excel/', views.export_shipping_excel, name='export_shipping_excel'),
    path('upload-design/', views.upload_design_and_confirm, name='upload_design_and_confirm'),
    path('manual-create/', views.manual_order_create, name='manual_order_create'),
    path('check-customer/', views.check_customer_exists, name='check_customer_exists'),
    path('search-customer-orders/', views.search_customer_orders, name='search_customer_orders'),
    path('customer-name-autocomplete/', views.customer_name_autocomplete, name='customer_name_autocomplete'),
    path('debug-upload/', views.debug_upload, name='debug_upload'),
    path('settlement/', views.settlement_list, name='settlement_list'),
    path('accounting/', views.accounting_list, name='accounting_list'),
    path('<int:pk>/move-to-accounting/', views.move_to_accounting, name='move_to_accounting'),
    path('sales-status/', views.sales_status, name='sales_status'),
    path('<int:pk>/update-due-date/', views.update_order_due_date, name='update_order_due_date'),
    path('<int:pk>/update-shipping-info/', views.update_order_shipping_info, name='update_order_shipping_info'),
    path('<int:pk>/auto-register-address/request/', views.address_auto_register_request, name='address_auto_register_request'),
    path('<int:pk>/auto-register-address/status/<int:request_id>/', views.address_auto_register_status, name='address_auto_register_status'),
    path('ktalk/kanban/sync/', views.kakao_kanban_sync, name='kakao_kanban_sync'),
    path('ktalk/kanban/open/', views.kakao_open_request, name='kakao_open_request'),
    path('ktalk/kanban/open/poll/', views.kakao_open_poll, name='kakao_open_poll'),
    path('ktalk/address-extraction/poll/', views.address_extraction_poll, name='address_extraction_poll'),
    path('ktalk/address-extraction/result/', views.address_extraction_result, name='address_extraction_result'),
    path('<int:pk>/ship-notify/request/', views.ship_notify_request, name='ship_notify_request'),
    path('<int:pk>/ship-notify/status/<int:request_id>/', views.ship_notify_status, name='ship_notify_status'),
    path('ktalk/ship-notify/poll/', views.ship_notify_poll, name='ship_notify_poll'),
    path('ktalk/ship-notify/result/', views.ship_notify_result, name='ship_notify_result'),
    path('<int:pk>/kanban-update/', views.update_order_kanban_status, name='update_order_kanban_status'),
]
