# Generated by Django 4.2.25 on 2025-10-12 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='지출 일자')),
                ('category', models.CharField(choices=[('SHIPPING', '배송비'), ('ADVERTISING', '광고비'), ('MATERIALS', '재료비 추가 구매'), ('EQUIPMENT', '장비 구매/수리'), ('UTILITIES', '공과금'), ('RENT', '임대료'), ('OTHER', '기타')], max_length=20, verbose_name='지출 항목')),
                ('description', models.TextField(blank=True, verbose_name='상세 설명')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='지출 금액')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '지출',
                'verbose_name_plural': '지출들',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
