# Generated by Django 4.2.25 on 2025-10-12 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='매입 일자')),
                ('category', models.CharField(choices=[('TSHIRT', '티셔츠'), ('HOODIE', '후드티'), ('INK', '잉크'), ('PRINTER_SUPPLIES', '프린터 부자재'), ('OTHER', '기타')], max_length=20, verbose_name='매입 항목')),
                ('description', models.TextField(blank=True, verbose_name='상세 설명')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='매입 금액')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '매입',
                'verbose_name_plural': '매입들',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
