# Generated by Django 4.2.25 on 2025-10-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_purchase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': '지출', 'verbose_name_plural': '지출'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': '매입', 'verbose_name_plural': '매입'},
        ),
    ]
