# Generated by Django 4.2.25 on 2026-05-13 15:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0019_order_clothing_post_processing_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(verbose_name='거래일시')),
                ('depositor_name', models.CharField(max_length=100, verbose_name='입금자명')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='입금액')),
                ('balance', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='거래 후 잔액')),
                ('memo', models.CharField(blank=True, default='', max_length=200, verbose_name='적요')),
                ('transaction_id', models.CharField(help_text='팝빌 거래내역의 고유 식별자 (중복 방지)', max_length=100, unique=True, verbose_name='거래 고유번호')),
                ('match_status', models.CharField(choices=[('UNMATCHED', '미매칭'), ('AUTO_MATCHED', '자동매칭'), ('MANUAL_MATCHED', '수동매칭'), ('IGNORED', '무시')], default='UNMATCHED', max_length=20, verbose_name='매칭 상태')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='확인 일시')),
                ('confirmed_by', models.CharField(blank=True, default='', max_length=50, verbose_name='확인자')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='수신일시')),
                ('matched_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='orders.order', verbose_name='매칭된 주문')),
            ],
            options={
                'verbose_name': '입금 내역',
                'verbose_name_plural': '입금 내역',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='CashReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_type', models.CharField(choices=[('BIZ_NO', '사업자번호'), ('PHONE', '휴대폰번호'), ('CARD', '카드번호')], default='BIZ_NO', max_length=10, verbose_name='식별 유형')),
                ('identity_number', models.CharField(help_text='사업자번호, 휴대폰번호, 또는 카드번호', max_length=30, verbose_name='식별번호')),
                ('trade_type', models.CharField(choices=[('INCOME_DEDUCTION', '소득공제용'), ('EXPENDITURE_PROOF', '지출증빙용')], default='EXPENDITURE_PROOF', max_length=20, verbose_name='거래 유형')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='발급 금액')),
                ('issue_status', models.CharField(choices=[('PENDING', '발급 대기'), ('ISSUED', '발급 완료'), ('FAILED', '발급 실패'), ('CANCELED', '발급 취소')], default='PENDING', max_length=10, verbose_name='발급 상태')),
                ('popbill_receipt_id', models.CharField(blank=True, default='', max_length=100, verbose_name='팝빌 접수번호')),
                ('popbill_nts_confirm_num', models.CharField(blank=True, default='', max_length=100, verbose_name='국세청 승인번호')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='오류 메시지')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='발급일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_receipts', to='orders.order', verbose_name='주문')),
            ],
            options={
                'verbose_name': '현금영수증',
                'verbose_name_plural': '현금영수증',
                'ordering': ['-created_at'],
            },
        ),
    ]
