# Generated by Django 4.2.25 on 2026-05-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popbill_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='bcode',
            field=models.CharField(blank=True, db_index=True, default='', help_text='뱅크다 데이터 일련번호 (증분/중복 방지)', max_length=50, verbose_name='뱅크다 bcode'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='원본 응답'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='source',
            field=models.CharField(choices=[('BANKDA', '뱅크다'), ('MANUAL', '수동'), ('POPBILL', '팝빌')], default='BANKDA', max_length=20, verbose_name='출처'),
        ),
        migrations.AddConstraint(
            model_name='deposit',
            constraint=models.UniqueConstraint(condition=models.Q(('bcode__gt', '')), fields=('source', 'bcode'), name='unique_source_bcode'),
        ),
    ]
