# Generated by Django 4.2.25 on 2025-10-12 08:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smartstore_order_id', models.CharField(help_text='스마트스토어에서 제공하는 고유 주문 ID', max_length=100, unique=True, verbose_name='스마트스토어 주문 ID')),
                ('status', models.CharField(choices=[('NEW', '신규 주문'), ('CONSULTING', '상담/시안 제작 중'), ('CONFIRMED', '고객 컨펌 완료'), ('PRODUCING', '제작 중'), ('PRODUCED', '제작 완료'), ('SHIPPED', '발송 완료'), ('COMPLETED', '정산 완료'), ('CANCELED', '주문 취소')], default='NEW', max_length=20, verbose_name='주문 상태')),
                ('payment_date', models.DateTimeField(verbose_name='결제일시')),
                ('customer_name', models.CharField(max_length=100, verbose_name='고객명')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='연락처')),
                ('shipping_address', models.TextField(verbose_name='배송 주소')),
                ('total_order_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='총 결제 금액')),
                ('confirmed_date', models.DateTimeField(blank=True, null=True, verbose_name='고객 컨펌 완료일시')),
                ('due_date', models.DateField(blank=True, help_text='컨펌일로부터 +3 영업일', null=True, verbose_name='발송 마감 예정일')),
                ('google_drive_folder_url', models.URLField(blank=True, help_text='시안/원본 통합 관리용', null=True, verbose_name='구글 드라이브 폴더 링크')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문들',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smartstore_product_name', models.CharField(help_text='원본 데이터 보존용', max_length=200, verbose_name='스마트스토어 제품명')),
                ('smartstore_option_text', models.TextField(help_text='스마트스토어에서 넘어온 원본 옵션 텍스트', verbose_name='스마트스토어 옵션 텍스트')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='개당 판매 가격')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='주문 시점의 ProductOption.base_cost를 복사하여 저장', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='개당 원가')),
                ('design_image_url', models.URLField(blank=True, help_text='해당 항목의 시안/원본 이미지 개별 링크', null=True, verbose_name='시안/원본 이미지 링크')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='주문')),
                ('product_option', models.ForeignKey(blank=True, help_text='관리자가 매핑한 내부 제품 옵션', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productoption', verbose_name='제품 옵션')),
            ],
            options={
                'verbose_name': '주문 항목',
                'verbose_name_plural': '주문 항목들',
                'ordering': ['order', 'id'],
            },
        ),
    ]
