# Generated by Django 4.2.25 on 2025-10-13 10:49

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-payment_date'], 'verbose_name': '주문', 'verbose_name_plural': '주문'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['order', 'id'], 'verbose_name': '주문 항목', 'verbose_name_plural': '주문 항목'},
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=3500, help_text='기본 3,500원 (제주/도서산간 변경 가능)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='택배비'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='manual_text',
            field=models.TextField(blank=True, default='', help_text='제품 옵션을 선택하지 않고 수동으로 입력한 항목 또는 메모', verbose_name='수동 입력 항목 (메모)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='결제일시'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_order_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='총 결제 금액 (택배비 포함)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='수량'),
        ),
    ]
