# Generated by Django 4.2.25 on 2025-10-13 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=0, default=3500, help_text='기본 3,500원 (제주/도서산간 변경 가능)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='택배비'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_order_amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='총 결제 금액 (택배비 포함)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=0, help_text='주문 시점의 ProductOption.base_cost를 복사하여 저장', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='개당 원가'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='개당 판매 가격'),
        ),
    ]
