# Generated by Django 4.2.25 on 2025-10-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='thumbnail_image',
            field=models.ImageField(blank=True, help_text='주문 상세 페이지 상단에 표시될 시안 썸네일', null=True, upload_to='order_thumbnails/', verbose_name='썸네일 이미지'),
        ),
    ]
