# Generated by Django 4.2.25 on 2025-10-13 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_thumbnail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='order_thumbnails/', verbose_name='썸네일 이미지')),
                ('order_number', models.PositiveIntegerField(default=1, verbose_name='순서')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일시')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='orders.order', verbose_name='주문')),
            ],
            options={
                'verbose_name': '주문 썸네일',
                'verbose_name_plural': '주문 썸네일',
                'ordering': ['order', 'order_number'],
            },
        ),
    ]
