# Generated by Django 4.2.25 on 2025-10-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderthumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderthumbnail',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='파일명'),
        ),
        migrations.AddField(
            model_name='orderthumbnail',
            name='google_drive_image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Google Drive 이미지 URL'),
        ),
        migrations.AlterField(
            model_name='orderthumbnail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='order_thumbnails/', verbose_name='썸네일 이미지'),
        ),
    ]
