# Generated by Django 4.2.25 on 2025-10-27 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderthumbnail_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_memo',
            field=models.TextField(blank=True, default='', help_text='고객에 대한 특이사항이나 주문 관련 메모', verbose_name='고객 메모'),
        ),
        migrations.AddField(
            model_name='order',
            name='print_method',
            field=models.CharField(blank=True, choices=[('DTG', 'DTG (Direct to Garment)'), ('DTF', 'DTF (Direct to Film)')], help_text='DTG 또는 DTF 선택', max_length=10, null=True, verbose_name='인쇄 방법'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='', help_text='택배 송장 번호', max_length=100, verbose_name='송장번호'),
        ),
        migrations.CreateModel(
            name='OrderCompletionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='completion_photos/', verbose_name='완료 사진')),
                ('google_drive_image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Google Drive 이미지 URL')),
                ('filename', models.CharField(blank=True, max_length=255, null=True, verbose_name='파일명')),
                ('order_number', models.PositiveIntegerField(default=1, verbose_name='순서')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일시')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_photos', to='orders.order', verbose_name='주문')),
            ],
            options={
                'verbose_name': '제작 완료 사진',
                'verbose_name_plural': '제작 완료 사진',
                'ordering': ['order', 'order_number'],
            },
        ),
    ]
