# Generated by Django 4.2.25 on 2025-11-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', '신규 주문'), ('CONSULTING', '상담/시안 제작 중'), ('PRODUCING', '제작 중'), ('PRODUCED', '제작 완료 (발송 대기)'), ('COMPLETED', '완료'), ('SETTLED', '정산 목록'), ('ARCHIVED', '종료 목록 (보관)'), ('CANCELED', '주문 취소')], default='NEW', max_length=20, verbose_name='주문 상태'),
        ),
    ]
