# Generated by Django 4.2.25 on 2025-12-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_date',
            field=models.DateField(blank=True, help_text='실제로 발송한 날짜 (캘린더에서 선택)', null=True, verbose_name='실제 발송일'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='연락처'),
        ),
    ]
