# Generated by Django 4.2.25 on 2026-03-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_merge_archived_into_settled'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_stat_paym_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_due_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_cust_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_payment_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_updated_idx',
        ),
    ]
