# Generated by Django 4.2.25 on 2026-06-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_shipnotifyrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressextractionrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', '등록'), ('CONSULTING', '결제'), ('PREP', '제작준비'), ('PRODUCED', '제작중'), ('COMPLETED', '발송'), ('SETTLED', '결과통보'), ('ARCHIVED', '정산 목록'), ('CANCELED', '주문 취소')], default='NEW', max_length=20, verbose_name='주문 상태'),
        ),
        migrations.AlterField(
            model_name='shipnotifyrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
