# Generated by Django 4.2.25 on 2026-06-05 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_addressextractionrequest_id_alter_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KakaoConsultCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=64, unique=True, verbose_name='카톡 고유 ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='카톡 대화명')),
                ('state', models.CharField(choices=[('WAITING', '대기중'), ('CONSULTING', '상담중')], default='WAITING', max_length=20, verbose_name='카톡 상태')),
                ('last_message_at', models.CharField(blank=True, default='', help_text='ktalk ingested_at 스냅샷 (재방문 판정용)', max_length=40, verbose_name='마지막 카톡 활동')),
                ('dismissed_at', models.DateTimeField(blank=True, help_text='1a-2b: 상담완료 처리 시각. 이후 새 메시지 오면 재등장', null=True, verbose_name='상담완료/숨김 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kakao_cards', to='orders.order', verbose_name='연동 주문')),
            ],
            options={
                'verbose_name': '카톡 상담 카드',
                'verbose_name_plural': '카톡 상담 카드',
                'ordering': ['-updated_at'],
            },
        ),
    ]
