# Generated by Django 4.2.25 on 2026-06-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_kakaoconsultcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='kakaoconsultcard',
            name='unread_count',
            field=models.IntegerField(default=0, verbose_name='안 읽은 메시지 수'),
        ),
    ]
