# Generated by Django 4.2.25 on 2026-06-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_kakaoconsultcard_unread_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='KakaoOpenRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=64, verbose_name='카톡 고유 ID')),
                ('status', models.CharField(default='PENDING', help_text='PENDING → DONE', max_length=20, verbose_name='처리 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일시')),
            ],
            options={
                'verbose_name': '카톡창 열기 요청',
                'verbose_name_plural': '카톡창 열기 요청',
                'ordering': ['created_at'],
            },
        ),
    ]
