# Generated by Django 4.2.25 on 2026-06-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_kakaoopenrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kakao_customer_id',
            field=models.CharField(blank=True, default='', help_text='ktalk 매칭으로 연결된 카톡 customer_id (카톡창 열기용). 빈값=매칭 실패', max_length=64, verbose_name='카톡 고유 ID'),
        ),
    ]
