# Generated by Django 4.2.25 on 2025-10-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='설정명')),
                ('google_drive_credentials_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Google Drive 서비스 계정 키 파일 경로')),
                ('google_drive_parent_folder_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Google Drive 상위 폴더 ID')),
                ('smartstore_client_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='스마트스토어 클라이언트 ID')),
                ('smartstore_client_secret', models.CharField(blank=True, max_length=200, null=True, verbose_name='스마트스토어 클라이언트 시크릿')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': 'API 설정',
                'verbose_name_plural': 'API 설정들',
                'ordering': ['-updated_at'],
            },
        ),
    ]
