# Generated by Django 4.2.25 on 2025-10-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisettings',
            name='oauth_credentials_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='OAuth 2.0 Credentials JSON 파일 경로'),
        ),
        migrations.AddField(
            model_name='apisettings',
            name='oauth_token_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='OAuth 2.0 토큰 저장 경로'),
        ),
        migrations.AddField(
            model_name='apisettings',
            name='use_oauth',
            field=models.BooleanField(default=False, verbose_name='OAuth 2.0 사용'),
        ),
    ]
