# Generated by Django 4.2.25 on 2025-10-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_apisettings_oauth_credentials_path_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apisettings',
            options={'ordering': ['-updated_at'], 'verbose_name': 'API 설정', 'verbose_name_plural': 'API 설정'},
        ),
    ]
