# Generated by Django 4.2.25 on 2025-10-12 08:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='예: 라운드 반팔 티셔츠', max_length=200, verbose_name='제품명')),
                ('is_active', models.BooleanField(default=True, help_text='제품이 판매 가능한 상태인지 여부', verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '제품',
                'verbose_name_plural': '제품들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_detail', models.CharField(help_text='예: 화이트 / L 사이즈', max_length=200, verbose_name='옵션 상세')),
                ('base_cost', models.DecimalField(decimal_places=2, default=0, help_text='관리자가 입력하는 기본 원가', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='기본 원가')),
                ('is_active', models.BooleanField(default=True, help_text='옵션이 판매 가능한 상태인지 여부', verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.product', verbose_name='제품')),
            ],
            options={
                'verbose_name': '제품 옵션',
                'verbose_name_plural': '제품 옵션들',
                'ordering': ['product', 'option_detail'],
                'unique_together': {('product', 'option_detail')},
            },
        ),
    ]
