# Generated by Django 4.2.25 on 2025-10-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GOODS', '굿즈 (시안 필요)'), ('GENERAL', '일반 (시안 불필요)')], default='GOODS', help_text='굿즈는 시안이 필요하고, 일반은 시안이 불필요합니다', max_length=10, verbose_name='카테고리'),
        ),
    ]
