# Generated by Django 4.2.25 on 2025-10-13 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': '제품', 'verbose_name_plural': '제품'},
        ),
        migrations.AlterModelOptions(
            name='productoption',
            options={'ordering': ['product', 'option_detail'], 'verbose_name': '제품 옵션', 'verbose_name_plural': '제품 옵션'},
        ),
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='제품의 기본 판매 가격 (옵션별로 다를 수 있음)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='기본 판매가'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='이 옵션의 판매 가격', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='판매가'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='base_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='이 옵션의 원가 (부가세 포함)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='제품 원가 (부가세 포함)'),
        ),
    ]
