# Generated by Django 4.2.25 on 2025-10-13 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_alter_productoption_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='제품의 기본 판매 가격 (옵션별로 다를 수 있음)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='기본 판매가'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='base_cost',
            field=models.DecimalField(decimal_places=0, default=0, help_text='이 옵션의 원가 (부가세 포함)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='제품 원가 (부가세 포함)'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='base_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='이 옵션의 판매 가격', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='판매가'),
        ),
    ]
