# Generated by Django 4.2.25 on 2025-10-13 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_cost',
            field=models.DecimalField(decimal_places=0, default=0, help_text='옵션이 없을 때 사용되는 기본 제품 원가', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='기본 원가'),
        ),
    ]
