# Generated by Django 4.2.25 on 2025-10-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_base_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='stock_quantity',
            field=models.IntegerField(blank=True, help_text='재고 수량 (NULL이면 무제한)', null=True, verbose_name='재고 수량'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='track_inventory',
            field=models.BooleanField(default=True, help_text='재고를 추적할지 여부 (프린터 잉크 등은 체크 해제)', verbose_name='재고 추적'),
        ),
    ]
