# Generated by Django 4.2.25 on 2025-12-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productoption_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_physical',
            field=models.BooleanField(default=True, help_text='실물 제품인지 여부 (캘린더에서 개수 집계 시 사용)', verbose_name='실물'),
        ),
    ]
